### ISSUE TITLE
Problem with empty output

### ISSUE THREAD

**Issue by johnSchnake** [vladimirvivien/gexe#41]
In some situation (presumably command failures) the `p.output` reader can be nil meaning that p.Result() will panic as it did here:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4f6475]
goroutine 1 [running]:
bytes.(*Buffer).ReadFrom(0xc00049c4e0, {0x0, 0x0})
	/usr/local/go/src/bytes/buffer.go:204 +0x75
github.com/vladimirvivien/gexe/exec.(*Proc).Result(0xc0004b0150)
	/home/prow/go/pkg/mod/github.com/vladimirvivien/gexe@v0.1.0/exec/proc.go:217 +0xa8
sigs.k8s.io/e2e-framework/support/kind.(*Cluster).Create(0xc0003e3680)
	/home/prow/go/src/sigs.k8s.io/e2e-framework/support/kind/kind.go:64 +0x226
sigs.k8s.io/e2e-framework/examples/simple_API.TestMain.func1({0x14a9870, 0xc000040088}, 0xc00041dec0)
	/home/prow/go/src/sigs.k8s.io/e2e-framework/examples/simple_API/main_test.go:43 +0x18f
sigs.k8s.io/e2e-framework/pkg/env.action.run({0x20, {0xc00041a288, 0x1, 0x8}}, {0x14a9870, 0xc000040088}, 0xc0000e7e30)
	/home/prow/go/src/sigs.k8s.io/e2e-framework/pkg/env/action.go:48 +0x62
sigs.k8s.io/e2e-framework/pkg/env.(*testEnv).Run(0xc0003ffa40, 0xc00041a290)
	/home/prow/go/src/sigs.k8s.io/e2e-framework/pkg/env/env.go:246 +0x1b3
sigs.k8s.io/e2e-framework/examples/simple_API.TestMain(0x40cfb8814db37)
	/home/prow/go/src/sigs.k8s.io/e2e-framework/examples/simple_API/main_test.go:66 +0x25b
main.main()
	_testmain.go:87 +0x20f
FAIL	sigs.k8s.io/e2e-framework/examples/simple_API	7.139s
```

This is from a k8s issue I'm working on.

**Comment by johnSchnake** [comment]
This may have already been fixed even if not explicitly reported. I can repro with 0.1.0 but not 0.1.1.
